
 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
     shell: powershell.exe
    
     steps:
       - checkout
       - run: start-job {dotnet run --project C:\Users\circleci\project\MockServer\MockServer}
       - run: .\Tests\doc-downloader.tests.ps1
       - run: Receive-Job 1 

