version: 2.1

orbs:
  windows: circleci/windows@5.0

jobs:
  test-ps5:
    executor:
      name: windows/default
      size: "medium"
    steps:
      - checkout
      - run:
          name: "Run PowerShell 5.1 Tests"
          shell: powershell.exe
          command: |
            if ($composePath) {
                Write-Host "Using compose command: $composePath"
                $cmd = "$composePath -f docker-compose.versions.yml"
            } else {
                Write-Host "docker-compose not found. Downloading..."
                Invoke-WebRequest "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-windows-x86_64.exe" -OutFile "docker-compose.exe"
                $cmd = ".\docker-compose.exe -f docker-compose.versions.yml"
            }
            
            try {
                & { $args = "/c $cmd up --build --exit-code-from downloader-ps5 downloader-ps5"; Start-Process cmd.exe -ArgumentList $args -Wait -NoNewWindow }
            } finally {
                Write-Host "Tests finished. Printing MockServer logs..."
                & { $args = "/c $cmd logs mockserver-ps5"; Start-Process cmd.exe -ArgumentList $args -Wait -NoNewWindow }
            }

  test-ps6:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: "Run PowerShell 6 Tests"
          command: ./run-version-tests.sh downloader-ps6

  test-ps7:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: "Run PowerShell 7 Tests"
          command: ./run-version-tests.sh downloader-ps7

workflows:
  verify:
    jobs:
      - test-ps5
      - test-ps6
      - test-ps7
