version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: 
          command: |
            << parameters.powershell_version_setup >>
      - run: |
          $module = "C:\Program Files\WindowsPowerShell\Modules\Pester"
          takeown /F $module /A /R
          icacls $module /reset
          icacls $module /grant "*S-1-5-32-544:F" /inheritance:d /T
          Remove-Item -Path $module -Recurse -Force -Confirm:$false
      - run: |
          Install-Module -Name Pester -Force  
          Get-Host | Select-Object Version 
          dotnet build C:\Users\circleci\project\MockServer\MockServer 
          $job = start-job {dotnet run --project C:\Users\circleci\project\MockServer\MockServer}
          Start-Sleep 10
          .\Tests\doc-downloader.tests.ps1
          .\Tests\drive-axle-doc-downloader.tests.ps1
      - run: |
          Write-Host (Split-Path -Path $PSScriptRoot)
          $ProgressPreference = 'SilentlyContinue';
          Compress-Archive -Path "C:\Users\circleci\project\README.txt", "C:\Users\circleci\project\configurations.json", "C:\Users\circleci\project\*.ps1" -DestinationPath document-downloader.zip
      - store_artifacts:
          path: document-downloader.zip
          destination: document-downloader.zip


workflows:
  version: 2
  build_with_powershell_versions:
    jobs:
      - build:
          matrix:
            parameters:
              powershell_version_setup: ["$PSVersionTable"]
