version: 2.1

jobs:
  test-powershell-versions:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: "Run Multi-Version PowerShell Tests"
          command: ./run-version-tests.sh

workflows:
  verify:
    jobs:
      - test-powershell-versions
