
 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: 
      name: win/default     
      shell: powershell.exe
    
     steps:
       - checkout
       - run: |
          Install-Module -Name Pester -Force
          Get-Host | Select-Object Version 
          dotnet build C:\Users\circleci\project\MockServer\MockServer 
          $job = start-job {dotnet run --project C:\Users\circleci\project\MockServer\MockServer}
          Start-Sleep 10  
          Receive-Job $job
          .\Tests\doc-downloader.tests.ps1
