version: 2.1

orbs:
  win: circleci/windows@2.2.0

commands:
  powershell_version_setup:
    parameters:
      powershell_setup_steps:
        description: setup steps needed for the configured powershell version to run
        type: steps
        default: []
    steps:
      - steps: << parameters.powershell_setup_steps >>
        
  run_tests:
    steps:
      - run: |
          $module = "C:\Program Files\WindowsPowerShell\Modules\Pester"
          takeown /F $module /A /R
          icacls $module /reset
          icacls $module /grant "*S-1-5-32-544:F" /inheritance:d /T
          Remove-Item -Path $module -Recurse -Force -Confirm:$false
      - run: |
          Install-Module -Name Pester -Force  
          Get-Host | Select-Object Version 
          dotnet build C:\Users\circleci\project\MockServer\MockServer 
          $job = start-job {dotnet run --project C:\Users\circleci\project\MockServer\MockServer}
          Start-Sleep 10
          .\Tests\doc-downloader.tests.ps1
          .\Tests\drive-axle-doc-downloader.tests.ps1
      - run: |
          Write-Host (Split-Path -Path $PSScriptRoot)
          $ProgressPreference = 'SilentlyContinue';
          Compress-Archive -Path "C:\Users\circleci\project\README.txt", "C:\Users\circleci\project\configurations.json", "C:\Users\circleci\project\*.ps1" -DestinationPath document-downloader.zip
      - store_artifacts:
          path: document-downloader.zip
          destination: document-downloader.zip

jobs:
  build_powershell_five:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run_tests
  build_powershell_six:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - powershell_version_setup:
          powershell_setup_steps:
            - run: |
                choco install powershell-core
                choco uninstall powershell-core
                choco install powershell-core --version=6.2.4
                cd 'C:\Program Files\PowerShell\6'
                .\pwsh.exe
      - run_tests
  build_powershell_seven:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - powershell_version_setup:
          powershell_setup_steps:
            - run: |
                choco install powershell-core --version=7.3.0
                pwsh.exe
      - run_tests


workflows:
  version: 2
  build_with_powershell_versions:
    jobs:
      - build_powershell_five
      - build_powershell_six
      - build_powershell_seven
          

