version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: |
         $module = "C:\Program Files (x86)\WindowsPowerShell\Modules\Pester"
         takeown /F $module /A /R
         icacls $module /reset
         icacls $module /grant "*S-1-5-32-544:F" /inheritance:d /T
         Remove-Item -Path $module -Recurse -Force -Confirm:$false
      - run: |
         $module = "C:\Program Files\WindowsPowerShell\Modules\Pester"
         takeown /F $module /A /R
         icacls $module /reset
         icacls $module /grant "*S-1-5-32-544:F" /inheritance:d /T
         Remove-Item -Path $module -Recurse -Force -Confirm:$false
      - run: |
         Install-Module -Name Pester -Force  
         Get-Host | Select-Object Version 
         dotnet build C:\Users\circleci\project\MockServer\MockServer 
         $job = start-job {dotnet run --project C:\Users\circleci\project\MockServer\MockServer}
         Start-Sleep 10
         Invoke-Pester -Script .\Tests\doc-downloader.tests.ps1 -OutputFile .\Tests\Test.xml
      - store_test_results:
          path: .\Tests\Tests.xml
      - store_artifacts:
          path: .\Tests\Tests.xml 
